name: Build/Publish Image

on:
  push:
    branches:
      - master
    paths:
      - 'Makefile'
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Makefile'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Image
      run: make build
    - name: Login
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish Image
      if: ${{ github.event_name == 'push' }}
      run: make release
